### ISSUE TITLE
Could you share Frame-wise configuration experiment result if you have?

### ISSUE THREAD

**Issue by DennisInTw** [hmkx/HiNeRV#3]
hello, thanks for your good work.
From the paper description, the representation experiment is based on Patch-wise configuration.
I cannot find the Frame-wise configuration experiment result except for the ablation study to compare the frame-wise and patch-wise.

If you have frame-wise experiment results for UVG and Bunny datasets, could you please help share them?

Thanks.

**Comment by hmkx** [comment]
Thank you for your interest in our work!

Unfortunately, we only have results in the proposed patchwise configuration, except for those in the ablation study. And we are not able to provide additional results.

**Comment by DennisInTw** [comment]
hello, thanks for your quickly reply.

**Comment by DennisInTw** [comment]
hello, could you please help give some advice to configure frame-wise for training?

Thanks.
